### ISSUE TITLE
Upgrade Ruby from 2.2.2

### ISSUE THREAD

**Issue by alexmuller** [alphagov/support-api#105]
This is the only application on GOV.UK running Ruby 2.2.2, which is the oldest of the Ruby 2.2 series that we support.

Available versions are here: https://github.com/alphagov/govuk-puppet/blob/master/modules/govuk_rbenv/manifests/all.pp

**Comment by tijmenb** [comment]
We did this now :)

**Comment by alexmuller** [comment]
Yay! 👏 

Also thanks for teaching me that archived repos were a new GitHub thing.
